config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://dom35mm.com'
  site_title: Dom35mm Photography
  site_subtitle_1: 'Photographer (Film & Digital) based in Atlanta, GA'
  site_subtitle_2: ''
  site_description: ''
  site_email: dom35mm@cloudburst.anonaddy.com
  site_social_url: 'https://instagram.com/dom35mm'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: /assets/uploads/android-chrome-512x512.png
  site_ga4_id: ''
  seo:
    site_title: Dom35mm Photography
    site_description: >-
      My portfolio website for my film & digital photography, showcasing some of
      my favorite shots from over the years!
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: false
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 100
  jpeg:
    enabled: true
    quality: 100
i18n:
  site_language: en
  site_social_title: Instagram
